### ISSUE TITLE
인스톨?

### ISSUE THREAD

**Issue by ansk28** [wiki-chan/Social#1]
미디어위키 Social 요놈 플러그인 테스트 해보려고 했는대요..
쟤 위키에 1.25.2 버전인대 전 플러그인이 먹히지가 않내요..
혹시 https://www.mediawiki.org/wiki/Extension:SocialProfile 이 플러그인을 설치하고 별도로 Social 이 플러그인을 설치를 해야 동작하는건가요??;;

**Comment by wiki-chan-server** [comment]
이 플러그인은 SocialProfile의 fork로서, 아직 모든 사이트에서 작동을 보장하지는 않습니다. 둘 다 설치할 필요는 없습니다. 그리고, 단순히 '작동하지 않는다'는 이슈는 아무런 도움이 되지 않으며, 이곳은 당신의 문제를 누군가가 해결해주는 공간이 아닙니다. 플러그인 설치 방법은 미디어위키 사이트를 참조해 주세요.
