### ISSUE TITLE
내 아바타 등록 확장자 오류

### ISSUE THREAD

**Issue by psm7177** [wiki-chan/Social#6]
내 아바타 등록시에 .png, .jpg 형식이 아닌 다른 파일 형식을 올렸을때

'  ".$1" 형식의 파일은 올릴 수 없습니다. $2 형식만 사용할 수 있습니다. '

이와 같은 경고가 뜹니다.

**Comment by wiki-chan-server** [comment]
아바타 등록 시 png와 jpg만 받도록 한 것은 정책 상의 결정입니다. 이는 버그가 아닙니다.

경고 메시지가 이상하게 나오는 것은 최신 SocialProfile에서 수정되었으므로, 여기에 가져옵니다.

**Comment by wiki-chan-server** [comment]
58c8626 에서 수정됨
